id: swagger-api

info:
  name: Public Swagger API - Detect
  author: pdteam,c-sh0,landaboot
  severity: info
  description: Public Swagger API was detected.
  reference: https://swagger.io/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    verified: true
    shodan-query: http.title:"swagger"
  tags: exposure,api,swagger

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"
      - "{{BaseURL}}/default.html"
      - "{{BaseURL}}/doc.html"
      - "{{BaseURL}}/documentation.html"
      - "{{BaseURL}}/standard.html"
      - "{{BaseURL}}/index.html"
      - "{{BaseURL}}/index2.html"
      - "{{BaseURL}}/index3.html"
      - "{{BaseURL}}/swagger-ui/swagger-ui.js"
      - "{{BaseURL}}/swagger-ui/swagger.js"
      - "{{BaseURL}}/swagger-ui/index.html"
      - "{{BaseURL}}/v2/api-docs"
      - "{{BaseURL}}/v1/api-docs"
      - "{{BaseURL}}/v3/api-docs"
      - "{{BaseURL}}/v4/api-docs"
      - "{{BaseURL}}/v5/api-docs"
      - "{{BaseURL}}/v1/api_docs"
      - "{{BaseURL}}/v2/api_docs"
      - "{{BaseURL}}/v3/api_docs"
      - "{{BaseURL}}/v4/api_docs"
      - "{{BaseURL}}/v5/api_docs"
      - "{{BaseURL}}/swagger/swagger-ui.js"
      - "{{BaseURL}}/swagger-ui.js"
      - "{{BaseURL}}/swagger/ui/swagger-ui.js"
      - "{{BaseURL}}/swagger/ui/index"
      - "{{BaseURL}}/swagger/index.html"
      - "{{BaseURL}}/swagger-ui.html"
      - "{{BaseURL}}/swagger/swagger-ui.html"
      - "{{BaseURL}}/api/swagger-ui.html"
      - "{{BaseURL}}/api2/swagger-ui.html"
      - "{{BaseURL}}/api3/swagger-ui.html"
      - "{{BaseURL}}/api-docs/swagger.json"
      - "{{BaseURL}}/api-docs/swagger.yaml"
      - "{{BaseURL}}/api_docs/swagger.json"
      - "{{BaseURL}}/api_docs/swagger.yml"
      - "{{BaseURL}}/api_docs/swagger.yaml"
      - "{{BaseURL}}/api_docs/doc.json"
      - "{{BaseURL}}/api_docs/docs.json"
      - "{{BaseURL}}/api_docs/doc.yaml"
      - "{{BaseURL}}/api_docs/doc.yml"
      - "{{BaseURL}}/api_docs"
      - "{{BaseURL}}/api_docs/"
      - "{{BaseURL}}/swagger.json"
      - "{{BaseURL}}/swagger.yaml"
      - "{{BaseURL}}/swagger.yml"
      - "{{BaseURL}}/swagger/v1/swagger.json"
      - "{{BaseURL}}/swagger/v1/swagger.yaml"
      - "{{BaseURL}}/swagger/v1/swagger.yml"
      - "{{BaseURL}}/swagger/v2/swagger.json"
      - "{{BaseURL}}/swagger/v2/swagger.yaml"
      - "{{BaseURL}}/swagger/v2/swagger.yml"
      - "{{BaseURL}}/swagger/v3/swagger.json"
      - "{{BaseURL}}/swagger/v3/swagger.yaml"
      - "{{BaseURL}}/swagger/v3/swagger.yml"
      - "{{BaseURL}}/swagger/v4/swagger.json"
      - "{{BaseURL}}/swagger/v4/swagger.yaml"
      - "{{BaseURL}}/swagger/v4/swagger.yml"
      - "{{BaseURL}}/swagger/v5/swagger.json"
      - "{{BaseURL}}/swagger/v5/swagger.yaml"
      - "{{BaseURL}}/swagger/v5/swagger.yml"
      - "{{BaseURL}}/api/index.html"
      - "{{BaseURL}}/api/doc"
      - "{{BaseURL}}/api/docs/"
      - "{{BaseURL}}/api/swagger.json"
      - "{{BaseURL}}/api/swagger.yaml"
      - "{{BaseURL}}/api/swagger.yml"
      - "{{BaseURL}}/api/swagger/index.html"
      - "{{BaseURL}}/api/swagger/swagger-ui.html"
      - "{{BaseURL}}/api/api-docs/swagger.json"
      - "{{BaseURL}}/api/api-docs/swagger.yaml"
      - "{{BaseURL}}/api/api-docs/swagger.yml"
      - "{{BaseURL}}/api/swagger-ui/swagger.json"
      - "{{BaseURL}}/api/swagger-ui/swagger.yaml"
      - "{{BaseURL}}/api/swagger-ui/swagger.yml"
      - "{{BaseURL}}/api/apidocs/swagger.json"
      - "{{BaseURL}}/api/apidocs/swagger.yaml"
      - "{{BaseURL}}/api/apidocs/swagger.yml"
      - "{{BaseURL}}/api/swagger-ui/api-docs"
      - "{{BaseURL}}/api/doc.json"
      - "{{BaseURL}}/api/api-docs"
      - "{{BaseURL}}/api/apidocs"
      - "{{BaseURL}}/api/swagger"
      - "{{BaseURL}}/api/swagger/static/index.html"
      - "{{BaseURL}}/api/swagger-resources"
      - "{{BaseURL}}/api/swagger-resources/restservices/v2/api-docs"
      - "{{BaseURL}}/api/__swagger__/"
      - "{{BaseURL}}/rest/swagger.json"
      - "{{BaseURL}}/api/_swagger_/"
      - "{{BaseURL}}/api/spec/swagger.json"
      - "{{BaseURL}}/api/spec/swagger.yaml"
      - "{{BaseURL}}/api/spec/swagger.yml"
      - "{{BaseURL}}/api/swagger/ui/index"
      - "{{BaseURL}}/__swagger__/"
      - "{{BaseURL}}/_swagger_/"
      - "{{BaseURL}}/api/v1/swagger-ui/swagger.json"
      - "{{BaseURL}}/api/v1/swagger-ui/swagger.yaml"
      - "{{BaseURL}}/api/v1/swagger-ui/swagger.yml"
      - "{{BaseURL}}/swagger-resources/restservices/v2/api-docs"
      - "{{BaseURL}}/swagger-resources/restservices/v1/api-docs"
      - "{{BaseURL}}/swagger-resources/restservices/v3/api-docs"
      - "{{BaseURL}}/swagger-resources/restservices/v4/api-docs"
      - "{{BaseURL}}/swagger-resources/restservices/v5/api-docs"
      - "{{BaseURL}}/api/swagger_doc.json"
      - "{{BaseURL}}/api/swagger_doc2.json"
      - "{{BaseURL}}/api/swagger_doc3.json"
      - "{{BaseURL}}/docu"
      - "{{BaseURL}}/documentation"
      - "{{BaseURL}}/documentacao"
      - "{{BaseURL}}/documentacion"
      - "{{BaseURL}}/docs"
      - "{{BaseURL}}/swagger"
      - "{{BaseURL}}/api-doc"
      - "{{BaseURL}}/swagger/docs"
      - "{{BaseURL}}/swagger/doc"
      - "{{BaseURL}}/swagger/docs/v1"
      - "{{BaseURL}}/swagger/docs/v2"
      - "{{BaseURL}}/swagger/docs/v3"
      - "{{BaseURL}}/swagger/docs/v4"
      - "{{BaseURL}}/swagger/docs/v5"


    headers:
      Accept: "*/*"

    stop-at-first-match: false
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "swagger:"
          - "Swagger 2.0"
          - "\"swagger\":"
          - "Swagger UI"
          - "loadSwaggerUI"
          - "**token**:"
          - "openapi\":"
          - "id=\"swagger-ui"
          - "basePath\":"
        condition: or

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - " @version (v[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})"

# minor modifications by landaboot
